#!/bin/sh

SOURCE_REPO='https://github.com/jheddings/beaglebone'

# environment variables that affect the script
confirm=${confirm:=no}
dryrun=${dryrun:=no}
skiptest=${skiptest:=no}

################################################################################
msg() {
  echo "## $@ ##"
}

################################################################################
run() {
  echo ">> $@"

  if [ "$dryrun" != 'yes' ] ; then
    $@
  fi

  echo '<<'
}

################################################################################
prompt_to_continue() {
  while read -p 'Continue? [yn] ' confirm ; do
    case $confirm in
      [Yy]*) break ;;
      [Nn]*) exit ;;
      *) echo "Please answer yes or no." ;;
    esac
  done
}

################################################################################
## MAIN ENTRY
echo '** Welcome to the Device::BeagleBone self-installer **'
echo
echo 'This will install the Perl BeagleBone device module'
echo "from $SOURCE_REPO"
echo

if [ "$confirm" != 'yes' ] ; then
  prompt_to_continue
fi

################################################################################
# make sure we exit cleanly on any error
set -e

cleanup() {
  if [ -n "$STAGING_DIR" -a -d "$STAGING_DIR" ] ; then
    echo "removing staging folder: $STAGING_DIR"
    rm -Rf "$STAGING_DIR"
  fi
}

STAGING_DIR=`mktemp -d`
trap cleanup EXIT

################################################################################
# start the installation

# download the repo
msg "staging installation in $STAGING_DIR"
run git clone "$SOURCE_REPO" "$STAGING_DIR"
cd "$STAGING_DIR"

# setup the installation
if [ -z "$@" ] ; then
  msg "preparing default environment"
else
  msg "preparing environment using: $@"
fi

run perl Makefile.PL $@

#TODO install module dependencies?

msg "installing Device::BeagleBone..."
if [ "$skiptest" != 'yes' ] ; then
  run make test
fi

run make install

